### ISSUE TITLE
main property not working and updateing in es6

### ISSUE THREAD

**Issue by Harrymaguire22** [ZackCgl/viteapp#8]
theresd an issue wiwht the es6 module

**Comment by ZackCgl** [comment]
yeah rthat s rough bro

**Comment by Harrymaguire22** [comment]
How can i fix this

**Comment by ZackCgl** [comment]
> How can i fix this

Make it better

**Comment by Harrymaguire22** [comment]
> > How can i fix this
> 
> Make it better

Thanks!
